import './admin/ui/utils/form/formFieldsGenerator.test'
import './admin/ui/utils/form/processFormFieldsValues.test'
import './admin/ui/utils/table/tableFieldsGenerator.test'
import './admin/collections/schemas/utils.test'
import './admin/collections/Changelog.test'
